# Generated by Django 3.2.7 on 2021-11-05 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='u_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
